const genreList = [
  "Adult Contemporary",
  "Alternative",
  "Blues/R&B",
  "Books & Spoken",
  "Children's Music",
  "Classical",
  "Country",
  "Dance",
  "Easy Listening",
  "Electronic",
  "Folk",
  "Fusion",
  "Hip Hop/Rap",
  "Holiday",
  "House",
  "Industrial",
  "Jazz",
  "New Age",
  "Pop",
  "Prog-Rock/Art Rock",
  "Religious",
  "Rock",
  "Soundtrack",
  "Techno",
  "Trance",
  "Unclassifiable",
  "World",
];

export default genreList;
