const genreList = [
  { id: 1, genreName: "Adult Contemporary" },
  { id: 2, genreName: "Alternative" },
  { id: 3, genreName: "Blues/R&B" },
  { id: 4, genreName: "Books & Spoken" },
  { id: 5, genreName: "Children's Music" },
  { id: 6, genreName: "Classical" },
  { id: 7, genreName: "Country" },
  { id: 8, genreName: "Dance" },
  { id: 9, genreName: "Easy Listening" },
  { id: 10, genreName: "Electronic" },
  { id: 11, genreName: "Folk" },
  { id: 12, genreName: "Fusion" },
  { id: 13, genreName: "Hip Hop/Rap" },
  { id: 14, genreName: "Holiday" },
  { id: 15, genreName: "House" },
  { id: 16, genreName: "Industrial" },
  { id: 17, genreName: "Jazz" },
  { id: 18, genreName: "New Age" },
  { id: 19, genreName: "Pop" },
  { id: 20, genreName: "Prog-Rock/Art Rock" },
  { id: 21, genreName: "Religious" },
  { id: 22, genreName: "Rock" },
  { id: 23, genreName: "Soundtrack" },
  { id: 24, genreName: "Techno" },
  { id: 25, genreName: "Trance" },
  { id: 26, genreName: "Unclassifiable" },
  { id: 27, genreName: "World" },
];

export default genreList;
