const genreList = [
  { id: 1, value: "Adult Contemporary" },
  { id: 2, value: "Alternative" },
  { id: 3, value: "Blues/R&B" },
  { id: 4, value: "Books & Spoken" },
  { id: 5, value: "Children's Music" },
  { id: 6, value: "Classical" },
  { id: 7, value: "Country" },
  { id: 8, value: "Dance" },
  { id: 9, value: "Easy Listening" },
  { id: 10, value: "Electronic" },
  { id: 11, value: "Folk" },
  { id: 12, value: "Fusion" },
  { id: 13, value: "Hip Hop/Rap" },
  { id: 14, value: "Holiday" },
  { id: 15, value: "House" },
  { id: 16, value: "Industrial" },
  { id: 17, value: "Jazz" },
  { id: 18, value: "New Age" },
  { id: 19, value: "Pop" },
  { id: 20, value: "Prog-Rock/Art Rock" },
  { id: 21, value: "Religious" },
  { id: 22, value: "Rock" },
  { id: 23, value: "Soundtrack" },
  { id: 24, value: "Techno" },
  { id: 25, value: "Trance" },
  { id: 26, value: "Unclassifiable" },
  { id: 27, value: "World" },
];

export default genreList;
