import { ReactChild, ReactFragment, ReactPortal } from "react";
import Head from "next/head";

export default function Header(props: {
  title: boolean | ReactChild | ReactFragment | ReactPortal | null | undefined;
}): JSX.Element {
  return (
    <Head>
      <title>{props.title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
