import Head from "next/head";

type Props = {
  title: string;
};

export default function Header(props: Props): JSX.Element {
  const { title } = props;

  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
